### ISSUE TITLE
vscode marketplace?

### ISSUE THREAD

**Issue by mjsisley** [lXSPandora/vscode-styled-components-snippets#1]
These look great. Do you plan to publish them to the vscode marketplace? They don't appear to be discoverable. https://marketplace.visualstudio.com/search?term=styled-components&target=VSCode&category=All%20categories&sortBy=Relevance

**Comment by lXSPandora** [comment]
Yes i will put on market place soon

**Comment by lXSPandora** [comment]
https://marketplace.visualstudio.com/items?itemName=lXSPandora.vscode-styled-components-snippets
